# Generated by Django 4.0.4 on 2022-05-11 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameusers',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='gameusers',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gameusers',
            name='uuid',
        ),
    ]
