import Head from 'next/head';
import Image from 'next/image';
import { motion } from 'framer-motion';

const LoadingAnimation = (props) => {
    return (
        <>
            <Head>
                <title>Game Hub</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='h-screen flex items-center justify-center'>
                <motion.div initial={{opacity: 0}} animate={{opacity: 1, scale: [0.9, 1, 0.11],  transition: {duration: 0.8, delay: 0.1}}}>
                    <Image src="/gameHubPlayIcon.svg" width={200} height={200} />
                </motion.div>
            </div>
        </>
    )
}

export default LoadingAnimation;