import Head from 'next/head';
import Image from 'next/image';
import { motion } from 'framer-motion';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

const LoadingAnimation = (props) => {
    const router = useRouter();

    useEffect(() => {
  
      setTimeout(() => router.push('/home'), 2200);
  
    }, [])
    return (
        <div className='relative'>
            <Head>
                <title>Game Hub</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='absolute w-full h-screen flex items-center justify-center'>
                <motion.div initial={{opacity: 0}} animate={{opacity: 1, scale: [0.9, 1, 0.11], x: [0, 0, -56],  transition: {duration: 0.7, delay: 0.1}}} exit={{opacity: 0}}>
                    <Image src="/gameHubPlayIcon.svg" width={200} height={200} />
                </motion.div>
            </div>
            <div className='absolute w-full h-screen flex items-center justify-center'>
                <motion.div initial={{opacity: 0}} animate={{opacity: 1, transition: {delay: 0.97}}} exit={{opacity: 0}}>
                    <Image src="/LogoWithoutPlayIcon.svg" width={204} height={48} />
                </motion.div>
            </div>
        </div>
    )
}

export default LoadingAnimation;